package com.quakescope.domain.model

enum class SortOption {
    TIME_DESC,
    TIME_ASC,
    MAGNITUDE_DESC,
    MAGNITUDE_ASC,
    DEPTH_DESC,
    DEPTH_ASC,

    REAL_TIME_DESC,
    REAL_TIME_ASC,
    REAL_MAGNITUDE_DESC,
    REAL_MAGNITUDE_ASC,
    REAL_DEPTH_DESC,
    REAL_DEPTH_ASC,

    ESTIMATED_TIME_DESC,
    ESTIMATED_TIME_ASC,
    ESTIMATED_MAGNITUDE_DESC,
    ESTIMATED_MAGNITUDE_ASC,
    ESTIMATED_DEPTH_DESC,
    ESTIMATED_DEPTH_ASC,
}
